export const PRICING = [
  {
    id: 'price_1NQk5TLtGdPVhGLecVfQ7mn0',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1688618799,
    currency: 'usd',
    custom_unit_amount: null,
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: 'Open Source',
    product: 'prod_ODAQ8gmahOB4D3',
    recurring: {
      aggregate_usage: null,
      interval: 'month',
      interval_count: 1,
      trial_period_days: null,
      usage_type: 'licensed',
    },
    tax_behavior: 'unspecified',
    tiers_mode: null,
    transform_quantity: null,
    type: 'recurring',
    unit_amount: 0,
    unit_amount_decimal: '10000',
    custom_price: 'Free',
    description: 'Adopt distributed tracing in minutes',
  },
  {
    id: 'price_1NQk55LtGdPVhGLefU8AHqHr',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1688618775,
    currency: 'usd',
    custom_unit_amount: null,
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: 'Cloud',
    product: 'prod_ODAPbMOvPnQg23',
    recurring: {
      aggregate_usage: null,
      interval: 'month',
      interval_count: 1,
      trial_period_days: null,
      usage_type: 'licensed',
    },
    tax_behavior: 'unspecified',
    tiers_mode: null,
    transform_quantity: null,
    type: 'recurring',
    unit_amount: 10000,
    unit_amount_decimal: '20000',
    description: 'Manage and control your distributed tracing data',
  },
  {
    id: 'price_1NQk4eLtGdPVhGLeZsZDsCNz',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1688618748,
    currency: 'usd',
    custom_unit_amount: null,
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: 'Enterprise',
    product: 'prod_ODAPwZwKJTEeDm',
    recurring: {
      aggregate_usage: null,
      interval: 'month',
      interval_count: 1,
      trial_period_days: null,
      usage_type: 'licensed',
    },
    tax_behavior: 'unspecified',
    tiers_mode: null,
    transform_quantity: null,
    type: 'recurring',
    unit_amount: 0,
    unit_amount_decimal: '50000',
    custom_price: 'Contact Us',
    description: 'Mission critical distributed tracing for your organization',
  },
];
